version: 0.1.0.{build}
image:
- Visual Studio 2017
before_build:
- nuget restore RestSharp.sln
branches:
  only:
  - master
  - feature/dotnet-core
skip_tags: true
build:
  project: RestSharp.sln
  verbosity: minimal
